echo -e "===\n10s" >> time.log; { time python text2video_cmd.py --scenario test/test10.json --path video 2>1 ; } 2>> time.log
echo -e "===\n20s" >> time.log; { time python text2video_cmd.py --scenario test/test20.json --path video 2>1 ; } 2>> time.log
echo -e "===\n30s" >> time.log; { time python text2video_cmd.py --scenario test/test30.json --path video 2>1 ; } 2>> time.log
echo -e "===\n40s" >> time.log; { time python text2video_cmd.py --scenario test/test40.json --path video 2>1 ; } 2>> time.log
echo -e "===\n50s" >> time.log; { time python text2video_cmd.py --scenario test/test50.json --path video 2>1 ; } 2>> time.log
echo -e "===\n60s" >> time.log; { time python text2video_cmd.py --scenario test/test60.json --path video 2>1 ; } 2>> time.log
echo -e "===\n70s" >> time.log; { time python text2video_cmd.py --scenario test/test70.json --path video 2>1 ; } 2>> time.log
echo -e "===\n80s" >> time.log; { time python text2video_cmd.py --scenario test/test80.json --path video 2>1 ; } 2>> time.log
echo -e "===\n90s" >> time.log; { time python text2video_cmd.py --scenario test/test90.json --path video 2>1 ; } 2>> time.log
echo -e "===\n100s" >> time.log; { time python text2video_cmd.py --scenario test/test100.json --path video 2>1 ; } 2>> time.log
echo -e "===\n110s" >> time.log; { time python text2video_cmd.py --scenario test/test110.json --path video 2>1 ; } 2>> time.log
echo -e "===\n120s" >> time.log; { time python text2video_cmd.py --scenario test/test120.json --path video 2>1 ; } 2>> time.log
echo -e "===\n130s" >> time.log; { time python text2video_cmd.py --scenario test/test130.json --path video 2>1 ; } 2>> time.log
echo -e "===\n140s" >> time.log; { time python text2video_cmd.py --scenario test/test140.json --path video 2>1 ; } 2>> time.log
echo -e "===\n150s" >> time.log; { time python text2video_cmd.py --scenario test/test150.json --path video 2>1 ; } 2>> time.log
echo -e "===\n160s" >> time.log; { time python text2video_cmd.py --scenario test/test160.json --path video 2>1 ; } 2>> time.log
echo -e "===\n170s" >> time.log; { time python text2video_cmd.py --scenario test/test170.json --path video 2>1 ; } 2>> time.log
echo -e "===\n180s" >> time.log; { time python text2video_cmd.py --scenario test/test180.json --path video 2>1 ; } 2>> time.log
